---

########################################################################
# Generate installation Jenkins jobs.
########################################################################

- name: "Generate AEM OpenCloud Jenkins job for installation configuration profile main libraries directory"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/mirror-aem-opencloud-libraries/
    state: directory
    mode: '0776'

- name: "Generate jobs for installation configuration profile AEM AWS Stack Builder Consolidated directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/mirror-stack-builder-libraries-{{ item.item.path }}/
    state: directory
    mode: '0776'
  with_items: "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"

- name: "Generate jobs for installation configuration profile AEM AWS Stack Builder Full-Set directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/mirror-stack-builder-libraries-{{ item.item.path }}/
    state: directory
    mode: '0776'
  with_items: "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"

- name: "Generate AEM OpenCloud Jenkins job for installation configuration profile main libraries config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/{{ item.path }}/config.xml
    mode: '0644'
  with_items:
    - { path: mirror-aem-opencloud-libraries, category: installation, platform_type: aws }

- name: "Generate jobs for installation configuration profile AEM AWS Stack Builder Consolidated config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-installation.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/mirror-stack-builder-libraries-{{ item.item.path }}/config.xml
    mode: '0644'
  with_items: "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"

- name: "Generate jobs for installation configuration profile AEM AWS Stack Builder Full-Set config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-installation.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/mirror-stack-builder-libraries-{{ item.item.path }}/config.xml
    mode: '0644'
  with_items: "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"

- name: "Generate jobs for installation configuration profile AEM AWS Stack Builder config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-installation.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/mirror-stack-builder-libraries-{{ item.item.path }}/config.xml
    mode: '0644'
  with_items: "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"

- name: "Generate AEM OpenCloud Jenkins job for installation configuration profile Packer AEM AWS resources directories"
  vars:
    library: packer-aem
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/{{ item[1] }}-{{ library }}-resources-{{ item[0].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ packer_aem_aws_resources_profiles_trimmed.results }}"
    - ["create", "delete"]

- name: "Generate AEM OpenCloud Jenkins job for installation configuration profile AEM AWS Stack Builder AWS resources directories"
  vars:
    library: aem-aws-stack-builder
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/{{ item[1] }}-{{ library }}-resources-{{ item[0].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aws_resources_profiles_trimmed.results }}"
    - ["create", "delete"]

- name: "Generate jobs for creating Packer AEM AWS resources config.xml"
  vars:
    library: packer-aem
  template:
    src: '../../../templates/ansible/jenkins/config/aws-resources-{{ library }}.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/{{ item[1] }}-{{ library }}-resources-{{ item[0].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ packer_aem_aws_resources_profiles_trimmed.results }}"
    - ["create", "delete"]

- name: "Generate jobs for creating AEM AWS Stack Builder AWS resources config.xml"
  vars:
    library: aem-aws-stack-builder
  template:
    src: '../../../templates/ansible/jenkins/config/aws-resources-{{ library }}.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/installation/aws/{{ item[1] }}-{{ library }}-resources-{{ item[0].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aws_resources_profiles_trimmed.results }}"
    - ["create", "delete"]
